---

- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: 'multiuser_cluster|default("true")|bool'
    - role: 'easybuild'
      EASYBUILD_PREFIX: '/opt/easybuild'
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: '/home'
          clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
        - path: '{{EASYBUILD_PREFIX}}'
          clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
    - slurm-master


- name: Slurm worker nodes Playbook
  hosts: slurm_worker
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: 'multiuser_cluster|default("true")|bool'
    - role: 'easybuild-deps'
    - role: 'lmod'
      vars:
        modules_root: '/opt/easybuild/modules/all'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
        - fs: '{{groups.slurm_master[0]}}:/opt/easybuild'
          mountpoint: '/opt/easybuild'
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: 'multiuser_cluster|default("true")|bool'
    - role: 'easybuild-deps'
    - role: 'lmod'
      vars:
        modules_root: '/opt/easybuild/modules/all'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
        - fs: '{{groups.slurm_master[0]}}:/opt/easybuild'
          mountpoint: '/opt/easybuild'
    - slurm-client


- name: Restart SLURMd after all config is done
  hosts: slurm_worker
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: 'is_debian_compatible and (is_debian_8_or_later or is_ubuntu_15_10_or_later)'
    - service:
        name=slurm-llnl
        state=restarted
      when: 'is_debian_compatible and not (is_debian_8_or_later or is_ubuntu_15_10_or_later)'
    - service:
        name=slurmd
        state=restarted
      when: is_rhel7_compatible
    - service:
        name=slurm
        state=restarted
      when: is_rhel6_compatible
