---

#
# Install EasyBuild
#

- name: Find out location of the `lmod` command
  shell: |
    set -e
    for script in modules.sh lmod.sh z00_lmod.sh; do
        if [ -r "/etc/profile.d/$script" ]; then
           . "/etc/profile.d/$script"
           break
        fi
    done
    if ! type module >/dev/null 2>/dev/null; then
        # error out if no 'module' command available
        exit 70
    fi
    echo -n $LMOD_DIR
  register: _eb_lmod_dir
  args:
    executable: /bin/bash

- name: Download bootstrap script
  get_url:
    url: '{{ easybuild_bootstrap_url }}'
    dest: '{{ easybuild_build_dir }}/bootstrap_eb.py'
    validate_certs: '{{ not insecure_https_downloads|default("no")|bool }}'


- name: Create required directories
  file:
    dest: '{{item}}'
    state: directory
    mode: 'ug+rwx,g+s'
    owner: '{{easybuild_user}}'
    group: 'easybuild'
  loop:
    - "{{ EASYBUILD_PREFIX }}/"
    - "{{ EASYBUILD_PREFIX }}/modules/all/EasyBuild/"
    - "{{ EASYBUILD_PREFIX }}/modules/tools/EasyBuild/"
    - "{{ EASYBUILD_PREFIX }}/software/"
    - "{{ EASYBUILD_PREFIX }}/sources/"
    - "{{ EASYBUILD_PREFIX }}/ebfiles/"


- name: Run the bootstrap script
  command: 'python3 {{ easybuild_build_dir }}/bootstrap_eb.py {{EASYBUILD_PREFIX}}'
  args:
    chdir:   '{{ easybuild_build_dir }}'
    creates: '{{EASYBUILD_PREFIX}}/software/EasyBuild/{{EASYBUILD_VERSION}}/bin/'
  # important that we don't run this step as `root`
  become: no
  environment:
    - EASYBUILD_MODULES_TOOL: Lmod
    - EASYBUILD_PREFIX: '{{EASYBUILD_PREFIX}}'
    # ensure Lmod is available
    - PATH: '{{ _eb_lmod_dir.stdout|default("/usr/share/lmod/libexec") }}:{{ansible_env.PATH}}'


- name: Build initial set of software
  shell: |
    set -e
    . /etc/profile.d/easybuild.sh
    for script in modules.sh lmod.sh z00_lmod.sh; do
        if [ -r "/etc/profile.d/$script" ]; then
           . "/etc/profile.d/$script"
           break
        fi
    done
    . "/etc/profile.d/$script"
    if ! type module; then
        # error out if no 'module' command available
        exit 70
    fi
    module load EasyBuild
    eb {{ EASYBUILD_INSTALL|join(' ') }}
  when: 'EASYBUILD_INSTALL|length > 0'
