---

- name: Set SLURM worker pam module params (Ubuntu >=20.04)
  set_fact:
    slurmd_pam_module_package: libpam-slurm-adopt
    slurmd_pam_module_so: pam_slurm_adopt.so
  when: is_ubuntu and (ansible_distribution_major_version|int >= 20)

  
- name: Set SLURM worker pam module params (older Debian/Ubuntu)
  set_fact:
    slurmd_pam_module_package: libpam-slurm
    slurmd_pam_module_so: pam_slurm.so
  when: slurmd_pam_module_package is undefined


- name: Set SLURM worker playbook params (Debian/Ubuntu)
  set_fact:
    slurmd_packages:
      - '{{ slurmd_pam_module_package }}'
      - slurmd
      - slurm-wlm-basic-plugins
  when: 'is_debian_8_or_later or is_ubuntu_15_10_or_later'


- name: Set SLURM worker playbook params (older Debian/Ubuntu)
  set_fact:
    slurmd_packages:
      - '{{ slurmd_pam_module_package }}'
      - slurm-llnl
      - slurm-llnl-basic-plugins
  when: 'is_debian_or_ubuntu and not (is_debian_8_or_later or is_ubuntu_15_10_or_later)'


- name: Set SLURM worker service name (Debian/Ubuntu)
  set_fact:
    slurmd_service: 'slurmd'
  when: 'is_debian_compatible and (is_debian_8_or_later or is_ubuntu_15_10_or_later)'


- name: Set SLURM worker service name (older Debian/Ubuntu)
  set_fact:
    slurmd_service: 'slurm-llnl'
  when: 'is_debian_compatible and not (is_debian_8_or_later or is_ubuntu_15_10_or_later)'
