# slurm-worker/tasks/main.yml
---

- name: Load distribution-specific parameters
  include_tasks: 'init-{{ansible_os_family}}.yml'

- name: Deploy SLURM configuration files
  tags:
    - slurm
  template:
    src: '{{item}}.j2'
    dest: '/etc/slurm/{{item}}'
    owner: root
    group: root
    mode: 0444
  loop:
    - gres.conf

- name: Deploy SLURM cgroup configuration
  tags:
    - slurm
    - slurm-worker
    - cgroups
  import_tasks: cgroup.yml
  when: '"cgroup" in slurm_taskplugin or "cgroup" in slurm_proctracktype or "cgroup" in slurm_jobacctgathertype'

- name: Install SLURM worker packages
  package:
    name: '{{slurmd_packages}}'
    state: '{{ pkg_install_state }}'

- name: Ensure SLURMd starts at boot
  service:
    name: '{{slurmd_service}}'
    enabled: yes

- name: Create /etc/ssh_allowed
  file:
    path: /etc/ssh_allowed
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Ensure ansible user always has SSH access
  lineinfile:
    path: /etc/ssh_allowed
    line: '{{ ansible_user }}'

- name: Setup sshd pam.d configuration
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^account\s+\w\s+{{ item.so }}'
    line: account {{ item.mode }} {{ item.so }} {{ item.options }}
  loop:
    - so: pam_listfile.so
      mode: sufficient
      options: item=user sense=allow onerr=fail file=/etc/ssh_allowed
    - so: '{{ slurmd_pam_module_so }}'
      mode: required
      options: ''
